### ISSUE TITLE
Missing translation items

### ISSUE THREAD

**Issue by westor7** [rocksdanister/lively-translations#63]
Hello,

Is it possible to support for translate the `On` + `Off` + `GO` text on these buttons ?

Images: 

![Image 1](https://i.imgur.com/UcQLrMx.png)

![Image 2](https://i.imgur.com/cwqp2ZE.png)

![Image 3](https://i.imgur.com/sEkgZZ8.png)

**Comment by rocksdanister** [comment]
Great suggestion!

**Regarding toggleswitches** 
The settings page is actually a UWP usercontrol and I couldn't manage to change its localization language that's why its like that.

Looks like its possible to set custom text:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/toggles
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.toggleswitch.offcontent?view=winrt-19041
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.toggleswitch.oncontent?view=winrt-19041

**Regarding GO button**
I'll replace it with Forward arrow E72A
https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font

**Comment by rocksdanister** [comment]
![Screenshot 2020-12-24 192339](https://user-images.githubusercontent.com/17554161/103092538-8f790100-461d-11eb-8187-4863fca0d1bc.png)

On/Off is pretty long in Greek 🤔

**Comment by rocksdanister** [comment]
Its done!
